-- dependencias: filas 1-66 de 66
insert into dependencias (id, empresa_a, empresa_b, tipo, porcentaje_suministro, es_critica, descripcion) values
  ('AAPL-2330', 'AAPL', '2330', 'proveedor', 90, true, 'Apple depende de TSMC para fabricar los chips A-series y M-series'),
  ('NVDA-2330', 'NVDA', '2330', 'proveedor', 92, true, 'NVIDIA depende de TSMC para fabricar sus GPUs de IA'),
  ('AMD-2330', 'AMD', '2330', 'proveedor', 88, true, 'AMD depende de TSMC para fabricar CPUs y GPUs'),
  ('QCOM-2330', 'QCOM', '2330', 'proveedor', 70, true, 'Qualcomm depende de TSMC para fabricar chips móviles Snapdragon'),
  ('2454-2330', '2454', '2330', 'proveedor', 85, true, 'MediaTek depende de TSMC para fabricar sus chips móviles'),
  ('2317-2330', '2317', '2330', 'proveedor', 40, false, 'Foxconn ensambla productos que dependen de chips fabricados por TSMC'),
  ('2330-ASML', '2330', 'ASML', 'proveedor', 95, true, 'TSMC depende de ASML como único proveedor de máquinas de litografía EUV'),
  ('005930-ASML', '005930', 'ASML', 'proveedor', 90, true, 'Samsung depende de ASML para fabricar chips avanzados'),
  ('INTC-ASML', 'INTC', 'ASML', 'proveedor', 85, true, 'Intel depende de ASML para su nueva generación de procesos avanzados'),
  ('000660-ASML', '000660', 'ASML', 'proveedor', 80, true, 'SK Hynix depende de ASML para fabricar memoria avanzada'),
  ('MU-ASML', 'MU', 'ASML', 'proveedor', 75, false, 'Micron depende de ASML para procesos de memoria de última generación'),
  ('2330-AMAT', '2330', 'AMAT', 'proveedor', 60, false, 'TSMC depende de equipos de fabricación de Applied Materials'),
  ('2330-LRCX', '2330', 'LRCX', 'proveedor', 55, false, 'TSMC usa equipos de grabado de Lam Research'),
  ('2330-KLAC', '2330', 'KLAC', 'proveedor', 50, false, 'TSMC depende de equipos de inspección de KLA'),
  ('2330-8035', '2330', '8035', 'proveedor', 60, false, 'TSMC usa equipos de recubrimiento y grabado de Tokyo Electron'),
  ('005930-8035', '005930', '8035', 'proveedor', 55, false, 'Samsung depende de equipos de fabricación de Tokyo Electron'),
  ('000660-AMAT', '000660', 'AMAT', 'proveedor', 50, false, 'SK Hynix depende de equipos de deposición de Applied Materials'),
  ('0981-ASML', '0981', 'ASML', 'proveedor', 30, true, 'SMIC depende de equipos de ASML, limitados por controles de exportación'),
  ('HUAWEI-0981', 'HUAWEI', '0981', 'proveedor', 60, true, 'Huawei depende de SMIC tras quedar excluida de TSMC por sanciones de EEUU'),
  ('0763-0981', '0763', '0981', 'proveedor', 45, true, 'ZTE depende de fundiciones chinas como SMIC por restricciones de exportación'),
  ('AAPL-2317', 'AAPL', '2317', 'proveedor', 65, true, 'Foxconn ensambla la mayoría de los iPhones'),
  ('AAPL-4938', 'AAPL', '4938', 'proveedor', 20, false, 'Pegatron es el segundo mayor ensamblador de iPhones'),
  ('AAPL-002475', 'AAPL', '002475', 'proveedor', 15, false, 'Luxshare ensambla AirPods y participa en el ensamblaje de iPhones'),
  ('1810-3231', '1810', '3231', 'proveedor', 30, false, 'Wistron ensambla parte de los smartphones de Xiaomi'),
  ('2357-4938', '2357', '4938', 'proveedor', 25, false, 'Pegatron, escindida de ASUS, ensambla parte de sus productos'),
  ('1810-QCOM', '1810', 'QCOM', 'proveedor', 55, true, 'Xiaomi depende de chips Snapdragon de Qualcomm en sus gamas altas'),
  ('1810-2454', '1810', '2454', 'proveedor', 40, false, 'Xiaomi usa chips MediaTek en gamas media y baja'),
  ('DELL-INTC', 'DELL', 'INTC', 'proveedor', 60, true, 'Dell depende de procesadores Intel para la mayoría de sus equipos'),
  ('DELL-AMD', 'DELL', 'AMD', 'proveedor', 25, false, 'Dell incorpora procesadores AMD en parte de su línea'),
  ('HPQ-INTC', 'HPQ', 'INTC', 'proveedor', 65, true, 'HP depende de procesadores Intel para la mayoría de sus PCs'),
  ('2357-INTC', '2357', 'INTC', 'proveedor', 50, false, 'ASUS depende de procesadores Intel en gran parte de su línea'),
  ('2357-AMD', '2357', 'AMD', 'proveedor', 30, false, 'ASUS incorpora procesadores AMD en su línea gaming'),
  ('2353-INTC', '2353', 'INTC', 'proveedor', 55, false, 'Acer depende de procesadores Intel en la mayoría de sus laptops'),
  ('CSCO-AVGO', 'CSCO', 'AVGO', 'proveedor', 40, false, 'Cisco depende de chips de red de Broadcom'),
  ('NVDA-000660', 'NVDA', '000660', 'proveedor', 60, true, 'NVIDIA depende de SK Hynix para memoria HBM en sus GPUs de IA'),
  ('NVDA-005930', 'NVDA', '005930', 'proveedor', 35, false, 'NVIDIA también usa memoria de Samsung en sus GPUs'),
  ('DELL-MU', 'DELL', 'MU', 'proveedor', 40, false, 'Dell depende de memoria de Micron para sus servidores y PCs'),
  ('AAPL-005930', 'AAPL', '005930', 'proveedor', 30, true, 'Apple depende de Samsung para memoria y pantallas OLED'),
  ('AAPL-034220', 'AAPL', '034220', 'proveedor', 25, false, 'Apple depende de LG Display para pantallas OLED del iPhone'),
  ('7203-6723', '7203', '6723', 'proveedor', 40, true, 'Toyota depende de Renesas para chips de control automotriz'),
  ('7267-6723', '7267', '6723', 'proveedor', 45, true, 'Honda depende de Renesas para semiconductores automotrices'),
  ('7201-6723', '7201', '6723', 'proveedor', 40, false, 'Nissan depende de Renesas para chips de control de vehículos'),
  ('BMW-IFX', 'BMW', 'IFX', 'proveedor', 45, true, 'BMW depende de Infineon para semiconductores de potencia'),
  ('VOW3-IFX', 'VOW3', 'IFX', 'proveedor', 40, true, 'Volkswagen depende de Infineon para chips automotrices'),
  ('MBG-IFX', 'MBG', 'IFX', 'proveedor', 40, false, 'Mercedes-Benz depende de Infineon para electrónica de potencia'),
  ('GM-ON', 'GM', 'ON', 'proveedor', 35, false, 'GM depende de ON Semiconductor para chips de potencia automotrices'),
  ('F-ON', 'F', 'ON', 'proveedor', 35, false, 'Ford depende de ON Semiconductor para semiconductores de vehículos'),
  ('RNO-STM', 'RNO', 'STM', 'proveedor', 40, false, 'Renault depende de STMicroelectronics para chips automotrices'),
  ('VOW3-CON', 'VOW3', 'CON', 'proveedor', 50, false, 'Volkswagen depende de Continental para sistemas electrónicos'),
  ('BMW-CON', 'BMW', 'CON', 'proveedor', 45, false, 'BMW depende de Continental para componentes y sensores'),
  ('TSLA-6752', 'TSLA', '6752', 'proveedor', 40, true, 'Tesla depende de Panasonic para celdas de batería'),
  ('TSLA-006400', 'TSLA', '006400', 'proveedor', 20, false, 'Tesla también usa baterías de Samsung SDI'),
  ('TSLA-ALB', 'TSLA', 'ALB', 'proveedor', 30, true, 'Tesla depende de Albemarle como proveedor de litio'),
  ('BMW-006400', 'BMW', '006400', 'proveedor', 35, true, 'BMW depende de Samsung SDI para baterías de vehículos eléctricos'),
  ('VOW3-006400', 'VOW3', '006400', 'proveedor', 30, false, 'Volkswagen depende de Samsung SDI para baterías EV'),
  ('6752-ALB', '6752', 'ALB', 'proveedor', 35, true, 'Panasonic depende de Albemarle como proveedor de litio para baterías'),
  ('1211-600111', '1211', '600111', 'proveedor', 25, false, 'BYD depende de tierras raras para motores de vehículos eléctricos'),
  ('AAPL-600111', 'AAPL', '600111', 'proveedor', 20, true, 'Apple depende de tierras raras chinas para imanes y hápticos'),
  ('SIE-600111', 'SIE', '600111', 'proveedor', 25, true, 'Siemens depende de tierras raras para motores eléctricos y turbinas'),
  ('6723-600111', '6723', '600111', 'proveedor', 15, false, 'Renesas depende parcialmente de tierras raras para componentes'),
  ('SHEL-XOM', 'SHEL', 'XOM', 'proveedor', 10, false, 'Coordinación limitada en infraestructura conjunta de refinación'),
  ('7203-XOM', '7203', 'XOM', 'proveedor', 15, false, 'Toyota depende de combustibles y lubricantes refinados'),
  ('VOD-ERICB', 'VOD', 'ERICB', 'proveedor', 40, false, 'Vodafone depende de Ericsson para infraestructura de red 5G'),
  ('BT-ERICB', 'BT', 'ERICB', 'proveedor', 35, false, 'BT depende de Ericsson para equipamiento de red'),
  ('9433-ERICB', '9433', 'ERICB', 'proveedor', 30, false, 'KDDI depende de Ericsson para infraestructura 5G'),
  ('0941-HUAWEI', '0941', 'HUAWEI', 'proveedor', 50, false, 'China Mobile depende de Huawei para infraestructura de red')
on conflict (id) do nothing;
