-- recursos_criticos: filas 1-14 de 14
insert into recursos_criticos (id, nombre, tipo, descripcion, principales_productores, dependencia_global, precio_actual, volatilidad) values
  ('IMANES', 'Imanes (Tierras Raras)', 'Mineral Crítico', 'Imanes de neodimio y samario para motores, turbinas eólicas, discos duros', '[{"pais":"China","porcentaje":85},{"pais":"Myanmar","porcentaje":10},{"pais":"Resto","porcentaje":5}]'::jsonb, 95, 85000, 'alta'),
  ('LITIO', 'Litio', 'Mineral Crítico', 'Componente esencial para baterías de iones de litio. Crítico para EV y almacenamiento', '[{"pais":"Chile","porcentaje":30},{"pais":"China","porcentaje":25},{"pais":"Argentina","porcentaje":20},{"pais":"Australia","porcentaje":15},{"pais":"Resto","porcentaje":10}]'::jsonb, 98, 18000, 'alta'),
  ('COBALTO', 'Cobalto', 'Mineral Crítico', 'Catalizador en refinerías, pigmentos, baterías recargables', '[{"pais":"Congo","porcentaje":70},{"pais":"Zambia","porcentaje":10},{"pais":"Resto","porcentaje":20}]'::jsonb, 92, 28000, 'alta'),
  ('COBRE', 'Cobre', 'Mineral Crítico', 'Conductor eléctrico. Crítico para electricidad, construcción, electrónica', '[{"pais":"Chile","porcentaje":28},{"pais":"Perú","porcentaje":12},{"pais":"China","porcentaje":9},{"pais":"Resto","porcentaje":51}]'::jsonb, 100, 9500, 'media'),
  ('SEMICONDUCTORES_CHIPS', 'Chips Semiconductores', 'Componente Crítico', '5nm, 7nm, 14nm para IA, computadoras, móviles. Fabricado por TSMC principalmente', '[{"pais":"Taiwán","porcentaje":92},{"pais":"Corea del Sur","porcentaje":5},{"pais":"Otros","porcentaje":3}]'::jsonb, 99, 450000, 'alta'),
  ('PETROLEO', 'Petróleo Crudo', 'Energía', 'Combustible fósil. Crítico para energía, transporte, químicos', '[{"pais":"Arabia Saudita","porcentaje":12},{"pais":"Rusia","porcentaje":11},{"pais":"EEUU","porcentaje":13},{"pais":"China","porcentaje":5},{"pais":"Irán","porcentaje":5},{"pais":"Resto","porcentaje":54}]'::jsonb, 85, 92, 'alta'),
  ('GAS_NATURAL', 'Gas Natural', 'Energía', 'Combustible fósil. Crítico para energía, calefacción, química', '[{"pais":"EEUU","porcentaje":23},{"pais":"Rusia","porcentaje":20},{"pais":"Qatar","porcentaje":12},{"pais":"Resto","porcentaje":45}]'::jsonb, 80, 3.2, 'alta'),
  ('SILICIO', 'Silicio', 'Mineral Crítico', 'Base de semiconductores, paneles solares, vidrio industrial', '[{"pais":"China","porcentaje":65},{"pais":"Rusia","porcentaje":15},{"pais":"Resto","porcentaje":20}]'::jsonb, 95, 2.5, 'media'),
  ('ALUMINIO', 'Aluminio', 'Mineral Crítico', 'Metal ligero. Crítico para aviación, construcción, automotriz, empaques', '[{"pais":"China","porcentaje":50},{"pais":"India","porcentaje":12},{"pais":"Rusia","porcentaje":10},{"pais":"Resto","porcentaje":28}]'::jsonb, 90, 2500, 'media'),
  ('ORO', 'Oro', 'Mineral', 'Conductor eléctrico en electrónica. Valor monetario', '[{"pais":"China","porcentaje":11},{"pais":"Australia","porcentaje":9},{"pais":"Rusia","porcentaje":6},{"pais":"Resto","porcentaje":74}]'::jsonb, 70, 2050, 'media'),
  ('PANTALLAS_OLED', 'Pantallas OLED', 'Componente Crítico', 'Pantallas para smartphones, TVs, wearables. Fabricadas por Samsung, LG', '[{"pais":"Corea del Sur","porcentaje":95},{"pais":"Otros","porcentaje":5}]'::jsonb, 98, 120000, 'media'),
  ('BATERIAS_LITIO', 'Baterías de Litio', 'Componente Crítico', 'Para EV, almacenamiento energético, dispositivos portátiles', '[{"pais":"China","porcentaje":75},{"pais":"Corea del Sur","porcentaje":15},{"pais":"Otros","porcentaje":10}]'::jsonb, 99, 150000, 'alta'),
  ('MEMORIA_DRAM', 'Memoria DRAM', 'Componente Crítico', 'Memoria RAM para computadoras, servidores, dispositivos', '[{"pais":"Corea del Sur","porcentaje":45},{"pais":"Japón","porcentaje":25},{"pais":"Taiwán","porcentaje":20},{"pais":"Otros","porcentaje":10}]'::jsonb, 100, 3.5, 'alta'),
  ('SSD_NAND', 'Almacenamiento SSD (NAND Flash)', 'Componente Crítico', 'Almacenamiento para computadoras, servidores, dispositivos móviles', '[{"pais":"China","porcentaje":35},{"pais":"Corea del Sur","porcentaje":35},{"pais":"Japón","porcentaje":20},{"pais":"Otros","porcentaje":10}]'::jsonb, 100, 0.08, 'media')
on conflict (id) do nothing;
