-- recursos_empresa: filas 1-91 de 91
insert into recursos_empresa (id, empresa_id, recurso_id, tipo, volumen_anual, porcentaje_produccion_global, descripcion) values
  ('ALB-LITIO-fabrica', 'ALB', 'LITIO', 'fabrica', 455372, 18, 'Albemarle es uno de los mayores productores mundiales de litio'),
  ('PLS-LITIO-fabrica', 'PLS', 'LITIO', 'fabrica', 13324, 8, 'Pilbara Minerals opera una de las mayores minas de litio del mundo'),
  ('TSLA-LITIO-depende', 'TSLA', 'LITIO', 'depende', 117065, 6, 'Tesla depende de litio para sus baterías de vehículos eléctricos'),
  ('6752-LITIO-depende', '6752', 'LITIO', 'depende', 182524, 4, 'Panasonic depende de litio para producir celdas de batería'),
  ('1211-LITIO-depende', '1211', 'LITIO', 'depende', 237665, 5, 'BYD depende de litio para su producción masiva de baterías LFP'),
  ('006400-LITIO-depende', '006400', 'LITIO', 'depende', 480639, 4, 'Samsung SDI depende de litio para baterías EV'),
  ('600111-IMANES-fabrica', '600111', 'IMANES', 'fabrica', 440575, 35, 'Mayor productora mundial de elementos de tierras raras'),
  ('AAPL-IMANES-depende', 'AAPL', 'IMANES', 'depende', 270244, 2, 'Apple depende de imanes de tierras raras para hápticos y altavoces'),
  ('SIE-IMANES-depende', 'SIE', 'IMANES', 'depende', 27788, 3, 'Siemens depende de imanes para motores eléctricos y turbinas eólicas'),
  ('1211-IMANES-depende', '1211', 'IMANES', 'depende', 221184, 3, 'BYD depende de imanes de tierras raras para motores EV'),
  ('6723-IMANES-depende', '6723', 'IMANES', 'depende', 405153, 1, 'Renesas usa componentes magnéticos en su producción'),
  ('GLEN-COBALTO-fabrica', 'GLEN', 'COBALTO', 'fabrica', 442990, 22, 'Glencore es el mayor productor mundial de cobalto'),
  ('006400-COBALTO-depende', '006400', 'COBALTO', 'depende', 159412, 5, 'Samsung SDI depende de cobalto para cátodos de batería'),
  ('6752-COBALTO-depende', '6752', 'COBALTO', 'depende', 24713, 4, 'Panasonic depende de cobalto para celdas de batería de alto rendimiento'),
  ('TSLA-COBALTO-depende', 'TSLA', 'COBALTO', 'depende', 14238, 3, 'Tesla busca reducir su dependencia de cobalto en nuevas químicas de batería'),
  ('FCX-COBRE-fabrica', 'FCX', 'COBRE', 'fabrica', 226272, 8, 'Uno de los mayores productores de cobre del mundo'),
  ('2899-COBRE-fabrica', '2899', 'COBRE', 'fabrica', 76763, 6, 'Zijin Mining opera importantes minas de cobre a nivel global'),
  ('RIO-COBRE-fabrica', 'RIO', 'COBRE', 'fabrica', 379200, 5, 'Rio Tinto produce cobre en múltiples operaciones globales'),
  ('BHP-COBRE-fabrica', 'BHP', 'COBRE', 'fabrica', 36422, 7, 'BHP opera Escondida, la mayor mina de cobre del mundo'),
  ('TECK-COBRE-fabrica', 'TECK', 'COBRE', 'fabrica', 452034, 3, 'Teck Resources produce cobre en Canadá y Chile'),
  ('GMEXICOB-COBRE-fabrica', 'GMEXICOB', 'COBRE', 'fabrica', 449940, 4, 'Mayor productora de cobre de México'),
  ('SIE-COBRE-depende', 'SIE', 'COBRE', 'depende', 444592, 2, 'Siemens depende de cobre para cableado y motores eléctricos'),
  ('ABBN-COBRE-depende', 'ABBN', 'COBRE', 'depende', 104833, 2, 'ABB depende de cobre para equipos eléctricos industriales'),
  ('2330-SEMICONDUCTORES_CHIPS-fabrica', '2330', 'SEMICONDUCTORES_CHIPS', 'fabrica', 160459, 60, 'TSMC fabrica la mayoría de los chips avanzados del mundo'),
  ('005930-SEMICONDUCTORES_CHIPS-fabrica', '005930', 'SEMICONDUCTORES_CHIPS', 'fabrica', 461738, 18, 'Segundo mayor fabricante mundial de semiconductores'),
  ('INTC-SEMICONDUCTORES_CHIPS-fabrica', 'INTC', 'SEMICONDUCTORES_CHIPS', 'fabrica', 237598, 10, 'Intel fabrica sus propios procesadores y busca ampliar su fundición'),
  ('0981-SEMICONDUCTORES_CHIPS-fabrica', '0981', 'SEMICONDUCTORES_CHIPS', 'fabrica', 171220, 5, 'Mayor fundición de China, limitada por controles de exportación'),
  ('2303-SEMICONDUCTORES_CHIPS-fabrica', '2303', 'SEMICONDUCTORES_CHIPS', 'fabrica', 471626, 4, 'Tercera mayor fundición de semiconductores del mundo'),
  ('GFS-SEMICONDUCTORES_CHIPS-fabrica', 'GFS', 'SEMICONDUCTORES_CHIPS', 'fabrica', 15526, 3, 'Fundición independiente con operaciones en EEUU, Alemania y Singapur'),
  ('AAPL-SEMICONDUCTORES_CHIPS-depende', 'AAPL', 'SEMICONDUCTORES_CHIPS', 'depende', 290823, 8, 'Apple depende de TSMC para todos sus chips propios'),
  ('NVDA-SEMICONDUCTORES_CHIPS-depende', 'NVDA', 'SEMICONDUCTORES_CHIPS', 'depende', 98042, 7, 'NVIDIA depende de fundiciones externas para fabricar sus GPUs'),
  ('DELL-SEMICONDUCTORES_CHIPS-depende', 'DELL', 'SEMICONDUCTORES_CHIPS', 'depende', 60752, 3, 'Dell depende de semiconductores para todos sus equipos'),
  ('7203-SEMICONDUCTORES_CHIPS-depende', '7203', 'SEMICONDUCTORES_CHIPS', 'depende', 97572, 2, 'Toyota depende de semiconductores automotrices, escasos en 2021-2022'),
  ('BMW-SEMICONDUCTORES_CHIPS-depende', 'BMW', 'SEMICONDUCTORES_CHIPS', 'depende', 418275, 2, 'BMW depende de semiconductores para sistemas electrónicos del vehículo'),
  ('XOM-PETROLEO-fabrica', 'XOM', 'PETROLEO', 'fabrica', 104072, 3, 'Una de las mayores productoras de petróleo del mundo'),
  ('CVX-PETROLEO-fabrica', 'CVX', 'PETROLEO', 'fabrica', 380399, 2, 'Chevron produce petróleo en múltiples cuencas globales'),
  ('SHEL-PETROLEO-fabrica', 'SHEL', 'PETROLEO', 'fabrica', 69063, 2, 'Shell es una de las petroleras integradas más grandes del mundo'),
  ('BP-PETROLEO-fabrica', 'BP', 'PETROLEO', 'fabrica', 372071, 2, 'BP produce y refina petróleo a escala global'),
  ('0857-PETROLEO-fabrica', '0857', 'PETROLEO', 'fabrica', 423901, 4, 'Mayor productora de petróleo de China'),
  ('NATIONAL-PETROLEO-exporta', 'NATIONAL', 'PETROLEO', 'exporta', 379588, 3, 'Exporta petróleo iraní bajo restricciones de sanciones internacionales'),
  ('PETR4-PETROLEO-fabrica', 'PETR4', 'PETROLEO', 'fabrica', 185254, 3, 'Petrobras lidera la producción de petróleo en aguas profundas de Brasil'),
  ('RELIANCE-PETROLEO-importa', 'RELIANCE', 'PETROLEO', 'importa', 242568, 2, 'Reliance importa y refina crudo en la mayor refinería del mundo'),
  ('ONGC-PETROLEO-fabrica', 'ONGC', 'PETROLEO', 'fabrica', 279332, 1, 'Mayor productora de petróleo y gas de India'),
  ('SU-PETROLEO-fabrica', 'SU', 'PETROLEO', 'fabrica', 19389, 1, 'Suncor produce petróleo a partir de arenas bituminosas canadienses'),
  ('PTT-PETROLEO-importa', 'PTT', 'PETROLEO', 'importa', 61333, 1, 'PTT importa petróleo para el mercado energético tailandés'),
  ('PEMEX-PETROLEO-fabrica', 'PEMEX', 'PETROLEO', 'fabrica', 294191, 2, 'Petrolera estatal mexicana'),
  ('7203-PETROLEO-depende', '7203', 'PETROLEO', 'depende', 470102, 1, 'Depende de derivados del petróleo para combustibles y plásticos'),
  ('SHEL-GAS_NATURAL-fabrica', 'SHEL', 'GAS_NATURAL', 'fabrica', 148310, 4, 'Shell es líder mundial en gas natural licuado (GNL)'),
  ('TTE-GAS_NATURAL-fabrica', 'TTE', 'GAS_NATURAL', 'fabrica', 237219, 3, 'TotalEnergies opera importantes proyectos de GNL'),
  ('WDS-GAS_NATURAL-fabrica', 'WDS', 'GAS_NATURAL', 'fabrica', 12052, 2, 'Mayor productora de gas natural de Australia'),
  ('NATIONAL-GAS_NATURAL-fabrica', 'NATIONAL', 'GAS_NATURAL', 'fabrica', 279073, 3, 'Irán tiene una de las mayores reservas de gas natural del mundo'),
  ('RWE-GAS_NATURAL-importa', 'RWE', 'GAS_NATURAL', 'importa', 471387, 2, 'RWE importa gas natural para generación eléctrica en Alemania'),
  ('PTT-GAS_NATURAL-importa', 'PTT', 'GAS_NATURAL', 'importa', 218471, 1, 'PTT importa GNL para el mercado tailandés'),
  ('2330-SILICIO-depende', '2330', 'SILICIO', 'depende', 221272, 15, 'TSMC depende de obleas de silicio de alta pureza'),
  ('005930-SILICIO-depende', '005930', 'SILICIO', 'depende', 363714, 12, 'Samsung depende de silicio para fabricación de chips'),
  ('INTC-SILICIO-depende', 'INTC', 'SILICIO', 'depende', 279536, 8, 'Intel depende de obleas de silicio para sus fábricas'),
  ('GFS-SILICIO-depende', 'GFS', 'SILICIO', 'depende', 372428, 3, 'GlobalFoundries depende de silicio de alta pureza'),
  ('RIO-ALUMINIO-fabrica', 'RIO', 'ALUMINIO', 'fabrica', 65680, 5, 'Rio Tinto es uno de los mayores productores de aluminio del mundo'),
  ('BHP-ALUMINIO-fabrica', 'BHP', 'ALUMINIO', 'fabrica', 324941, 2, 'BHP produce alúmina y aluminio en operaciones globales'),
  ('S32-ALUMINIO-fabrica', 'S32', 'ALUMINIO', 'fabrica', 200311, 2, 'South32 produce aluminio y alúmina'),
  ('VOW3-ALUMINIO-depende', 'VOW3', 'ALUMINIO', 'depende', 87958, 2, 'Volkswagen depende de aluminio para carrocerías más ligeras'),
  ('BMW-ALUMINIO-depende', 'BMW', 'ALUMINIO', 'depende', 410086, 2, 'BMW depende de aluminio para componentes estructurales'),
  ('F-ALUMINIO-depende', 'F', 'ALUMINIO', 'depende', 48736, 2, 'Ford usa aluminio extensivamente en su línea F-150'),
  ('NEM-ORO-fabrica', 'NEM', 'ORO', 'fabrica', 412887, 5, 'Mayor productora de oro del mundo'),
  ('ABX-ORO-fabrica', 'ABX', 'ORO', 'fabrica', 85974, 4, 'Una de las mayores mineras de oro del mundo'),
  ('AEM-ORO-fabrica', 'AEM', 'ORO', 'fabrica', 254065, 2, 'Importante productora de oro canadiense'),
  ('2899-ORO-fabrica', '2899', 'ORO', 'fabrica', 28141, 2, 'Zijin Mining también produce oro junto con cobre'),
  ('005930-PANTALLAS_OLED-fabrica', '005930', 'PANTALLAS_OLED', 'fabrica', 246194, 45, 'Mayor fabricante mundial de pantallas OLED'),
  ('034220-PANTALLAS_OLED-fabrica', '034220', 'PANTALLAS_OLED', 'fabrica', 186641, 25, 'Segundo mayor fabricante de pantallas OLED, principal proveedor de TVs'),
  ('000725-PANTALLAS_OLED-fabrica', '000725', 'PANTALLAS_OLED', 'fabrica', 471684, 15, 'BOE es el mayor fabricante de pantallas de China'),
  ('AAPL-PANTALLAS_OLED-depende', 'AAPL', 'PANTALLAS_OLED', 'depende', 79555, 10, 'Apple depende de Samsung y LG para pantallas OLED del iPhone'),
  ('1810-PANTALLAS_OLED-depende', '1810', 'PANTALLAS_OLED', 'depende', 244109, 4, 'Xiaomi depende de pantallas OLED de proveedores externos'),
  ('6758-PANTALLAS_OLED-depende', '6758', 'PANTALLAS_OLED', 'depende', 378251, 3, 'Sony depende de paneles OLED para sus televisores premium'),
  ('006400-BATERIAS_LITIO-fabrica', '006400', 'BATERIAS_LITIO', 'fabrica', 210742, 12, 'Samsung SDI es uno de los mayores fabricantes de baterías de litio'),
  ('6752-BATERIAS_LITIO-fabrica', '6752', 'BATERIAS_LITIO', 'fabrica', 199772, 10, 'Panasonic fabrica las celdas de batería usadas por Tesla'),
  ('TSLA-BATERIAS_LITIO-depende', 'TSLA', 'BATERIAS_LITIO', 'depende', 466823, 8, 'Tesla depende de baterías de litio para todos sus vehículos'),
  ('BMW-BATERIAS_LITIO-depende', 'BMW', 'BATERIAS_LITIO', 'depende', 226010, 4, 'BMW depende de baterías de litio para su línea de EVs'),
  ('VOW3-BATERIAS_LITIO-depende', 'VOW3', 'BATERIAS_LITIO', 'depende', 447889, 5, 'Volkswagen depende de baterías de litio para su transición a EVs'),
  ('1211-BATERIAS_LITIO-fabrica', '1211', 'BATERIAS_LITIO', 'fabrica', 166424, 15, 'BYD fabrica sus propias baterías LFP para vehículos eléctricos'),
  ('005930-MEMORIA_DRAM-fabrica', '005930', 'MEMORIA_DRAM', 'fabrica', 334916, 40, 'Mayor fabricante mundial de memoria DRAM'),
  ('000660-MEMORIA_DRAM-fabrica', '000660', 'MEMORIA_DRAM', 'fabrica', 230806, 28, 'Segundo mayor fabricante mundial de memoria DRAM'),
  ('MU-MEMORIA_DRAM-fabrica', 'MU', 'MEMORIA_DRAM', 'fabrica', 251959, 22, 'Tercer mayor fabricante mundial de memoria DRAM'),
  ('NVDA-MEMORIA_DRAM-depende', 'NVDA', 'MEMORIA_DRAM', 'depende', 369486, 8, 'NVIDIA depende de memoria HBM para sus GPUs de IA'),
  ('DELL-MEMORIA_DRAM-depende', 'DELL', 'MEMORIA_DRAM', 'depende', 54896, 4, 'Dell depende de memoria DRAM para servidores y PCs'),
  ('AAPL-MEMORIA_DRAM-depende', 'AAPL', 'MEMORIA_DRAM', 'depende', 398564, 5, 'Apple depende de memoria DRAM de Samsung y SK Hynix'),
  ('005930-SSD_NAND-fabrica', '005930', 'SSD_NAND', 'fabrica', 296706, 33, 'Líder mundial en fabricación de memoria NAND flash'),
  ('000660-SSD_NAND-fabrica', '000660', 'SSD_NAND', 'fabrica', 277806, 20, 'SK Hynix es uno de los mayores fabricantes de NAND flash'),
  ('KIOXIA-SSD_NAND-fabrica', 'KIOXIA', 'SSD_NAND', 'fabrica', 383632, 18, 'Kioxia (ex-Toshiba Memory) es líder histórico en NAND flash'),
  ('MU-SSD_NAND-fabrica', 'MU', 'SSD_NAND', 'fabrica', 305887, 12, 'Micron fabrica memoria NAND flash para almacenamiento SSD'),
  ('DELL-SSD_NAND-depende', 'DELL', 'SSD_NAND', 'depende', 209837, 4, 'Dell depende de NAND flash para almacenamiento en servidores y laptops'),
  ('HPQ-SSD_NAND-depende', 'HPQ', 'SSD_NAND', 'depende', 283703, 3, 'HP depende de almacenamiento SSD para sus equipos')
on conflict (id) do nothing;
