-- cuellos_botella: filas 1-17 de 17
insert into cuellos_botella (id, nombre, pais, latitud, longitud, tipo, criticidad, porcentaje_global, impacto_sectores, descripcion, vulnerabilidades, empresas_afectadas, consecuencias_si_falla, color) values
  ('taiwan-chips', 'Taiwán - Fabricación de Chips 5nm', 'Taiwán', 23.8978, 120.9605, 'Fabricación', 'CRÍTICA', 92, '["Semiconductores","IA","Smartphones","Cloud Computing"]'::jsonb, 'TSMC controla el 92% de la fabricación mundial de chips de 5nm y tecnologías más avanzadas', '["Conflicto US-China","Dependencia de un solo fabricante","Limitaciones geográficas de la isla","Amenaza de invasión"]'::jsonb, '["Apple","NVIDIA","AMD","MediaTek","Qualcomm"]'::jsonb, 'Colapso de industria de semiconductores mundial, detención de producción de IA, smartphones y computadoras', '#ff3333'),
  ('holanda-litografia', 'Holanda - Máquinas ASML', 'Países Bajos', 52.1326, 5.2913, 'Manufactura de Equipos', 'CRÍTICA', 100, '["Semiconductores","Tecnología"]'::jsonb, 'ASML es el único fabricante mundial de máquinas EUV (litografía de ultravioleta extremo) necesarias para producir chips modernos', '["Monopolio global de tecnología EUV","Sanciones a China limitan ventas","Depende de suministros alemanes de precisión","Capacidad de producción limitada"]'::jsonb, '["TSMC","Samsung","Intel","Todos los fabricantes de chips"]'::jsonb, 'Imposibilidad de fabricar chips avanzados en cualquier parte del mundo', '#ff3333'),
  ('ormuz-petroleo', 'Estrecho de Ormuz - Tránsito de Petróleo', 'Irán/Omán', 26.6, 56.5, 'Transporte de Recursos', 'CRÍTICA', 35, '["Energía","Transporte","Manufactura"]'::jsonb, 'El 35% del petróleo global transita por el Estrecho de Ormuz, punto estratégico controlado por Irán', '["Control geopolítico de Irán","Riesgo de cierre por conflicto regional","Única ruta viable sin alternativas cercanas","Ataques a petroleros frecuentes"]'::jsonb, '["Todas las petroleras","Transportistas globales","Manufactureras"]'::jsonb, 'Crisis energética global, colapso de precios del petróleo o escasez, parálisis económica', '#ff6600'),
  ('china-tierras-raras', 'China - Producción de Tierras Raras', 'China', 35.8617, 104.1954, 'Extracción de Recursos', 'CRÍTICA', 85, '["Electrónica","Defensa","Renovables","Tecnología"]'::jsonb, 'China produce el 85% de las tierras raras mundiales, elementos esenciales para imanes, baterías y tecnología', '["Dominio de China sobre producción","Restricciones de exportación como arma política","Daño ambiental extremo en minas chinas","Pocas alternativas globales"]'::jsonb, '["Tesla","Apple","Bosch","Vestas","Siemens","Todos fabricantes de tecnología"]'::jsonb, 'Detención de producción de dispositivos electrónicos, vehículos eléctricos y energías renovables', '#ff6600'),
  ('china-aluminio', 'China - Producción de Aluminio', 'China', 35.8617, 104.1954, 'Extracción de Recursos', 'ALTA', 65, '["Manufactura","Aviación","Automotriz","Construcción"]'::jsonb, 'China produce el 65% del aluminio global, material crítico para múltiples industrias', '["Producción concentrada en China","Restricciones de exportación posibles","Alto costo energético de extracción","Impacto ambiental en Xinjiang"]'::jsonb, '["Boeing","Airbus","Todos fabricantes de automóviles","Constructoras"]'::jsonb, 'Escasez de materiales para aviación, automotriz y construcción', '#ff6600'),
  ('siria-fosfato', 'Siria/Levante - Fosfato para Fertilizantes', 'Siria', 34.8021, 38.9968, 'Extracción de Recursos', 'ALTA', 50, '["Agricultura","Alimentación"]'::jsonb, 'Siria y Levante producen el 50% del fosfato mundial, esencial para fertilizantes y producción alimentaria', '["Conflicto regional en Levante","Minería afectada por guerra en Siria","Sanciones internacionales","Infraestructura dañada"]'::jsonb, '["Mosaic","CF Industries","Yara","Todos productores de alimentos"]'::jsonb, 'Crisis alimentaria global, reducción de producción agrícola, hambruna', '#ff6600'),
  ('panama-canal', 'Canal de Panamá - Comercio Global', 'Panamá', 9.0765, -79.5217, 'Transporte Comercial', 'ALTA', 6, '["Comercio","Logística","Manufactura"]'::jsonb, 'Canal de Panamá mueve el 6% del comercio global, conecta Atlántico y Pacífico', '["Control de Panamá sobre paso","Sequía afecta operaciones","Tensiones geopolíticas US-China","Capacidad limitada"]'::jsonb, '["Todos transportistas","Compañías navieras","Exportadores"]'::jsonb, 'Aumentar costos de transporte, desvío a Cabo de Hornos agrega 15 días', '#ff9900'),
  ('estrecho-malaca', 'Estrecho de Malaca - Tránsito de Petróleo y Comercio', 'Malasia/Singapur/Indonesia', 4, 102, 'Transporte de Recursos', 'ALTA', 30, '["Energía","Comercio","Transporte"]'::jsonb, 'El 30% del comercio global de petróleo y 25% del comercio internacional transita por Malaca', '["Piratería en aguas internacionales","Control de Singapur sobre paso","Ruta congestionada","Tensiones China-USA"]'::jsonb, '["Todas petroleras","Transportistas","Comercio asiático"]'::jsonb, 'Crisis energética, aumento de costos de transporte, ruptura comercial Asia-Europa', '#ff9900'),
  ('mineria-cobalto', 'República Democrática del Congo - Minería de Cobalto', 'Congo', -4.0383, 21.7587, 'Extracción de Recursos', 'ALTA', 70, '["Baterías","Vehículos Eléctricos","Electrónica"]'::jsonb, 'Congo produce el 70% del cobalto mundial, elemento esencial para baterías de iones de litio', '["Inestabilidad política y conflictos","Minería artesanal no regulada","Derechos humanos cuestionables","Minería de conflicto"]'::jsonb, '["Tesla","BMW","Apple","Samsung","Todos fabricantes de baterías"]'::jsonb, 'Crisis en producción de vehículos eléctricos, smartphones y dispositivos portátiles', '#ff9900'),
  ('singapur-refineria', 'Singapur - Refinería de Petróleo', 'Singapur', 1.3521, 103.8198, 'Procesamiento de Recursos', 'ALTA', 18, '["Energía","Petroquímica","Transporte"]'::jsonb, 'Singapur refina el 18% del petróleo global y es hub de petroquímicos asiático', '["Dependencia de suministros del Golfo","Localización en zona sísmica","Proximidad a rutas congestionadas","Impacto de tensiones China-USA"]'::jsonb, '["Shell","ExxonMobil","Todas petroleras","Transportistas"]'::jsonb, 'Crisis energética asiática, aumento de precios de gasolina y diésel', '#ff9900'),
  ('rusia-gas-natural', 'Rusia - Exportación de Gas Natural', 'Rusia', 61.52, 105.32, 'Extracción de Recursos', 'MEDIA', 40, '["Energía","Manufactura","Calefacción"]'::jsonb, 'Rusia exporta el 40% del gas natural global, especialmente a Europa', '["Sanciones internacionales","Dependencia de tuberías a través de Ucrania","Conflicto geopolítico con Occidente","Alternativas en desarrollo (LNG)"]'::jsonb, '["Gazprom","Rosneft","Utilidades europeas","Manufactureras"]'::jsonb, 'Crisis energética europea, desindustrialización, inflación energética', '#ffaa00'),
  ('australia-litio', 'Australia - Extracción de Litio', 'Australia', -25.2744, 133.7751, 'Extracción de Recursos', 'ALTA', 35, '["Baterías","Vehículos Eléctricos","Renovables"]'::jsonb, 'Australia produce el 35% del litio mundial, elemento crítico para baterías de EV', '["Demanda creciente de litio","Dependencia de China para procesamiento","Presión ambiental por minería","Volatilidad de precios"]'::jsonb, '["Tesla","Volkswagen","BYD","CATL","Todos fabricantes de EV"]'::jsonb, 'Freno en transición a vehículos eléctricos, crisis de baterías', '#ff9900'),
  ('chile-cobre', 'Chile - Minería de Cobre', 'Chile', -30.7, -71.5428, 'Extracción de Recursos', 'ALTA', 28, '["Electricidad","Electrónica","Construcción"]'::jsonb, 'Chile produce el 28% del cobre mundial, esencial para electricidad y electrónica', '["Inestabilidad política","Huelgas en minas","Escasez de agua en desiertos","Presión ambiental"]'::jsonb, '["Tesla","ABB","Siemens","Todas compañías de electricidad"]'::jsonb, 'Escasez de cobre, aumento de costos de infraestructura eléctrica', '#ff9900'),
  ('indonesia-niquel', 'Indonesia - Minería de Níquel', 'Indonesia', -0.7893, 113.9213, 'Extracción de Recursos', 'MEDIA', 35, '["Baterías","Acero Inoxidable","Electrónica"]'::jsonb, 'Indonesia produce el 35% del níquel mundial, esencial para baterías y acero', '["Prohibición de exportación de mineral sin procesar","Dependencia de procesamiento chino","Impacto ambiental extremo","Falta de infraestructura"]'::jsonb, '["Tesla","CATL","Ningbo Shanshan","Fabricantes de baterías"]'::jsonb, 'Crisis en producción de baterías de EV, restricción de cadena de suministro', '#ffaa00'),
  ('ucrania-trigo', 'Ucrania - Exportación de Trigo', 'Ucrania', 48.3794, 31.1656, 'Producción Agrícola', 'MEDIA', 12, '["Alimentación","Agricultura"]'::jsonb, 'Ucrania exporta el 12% del trigo global, exportador importante de granos', '["Invasión rusa, guerra en curso","Bloqueo naval del Mar Negro","Destrucción de infraestructura agrícola","Minas terrestres en campos"]'::jsonb, '["Todas compañías de alimentos","Distribuidoras de granos"]'::jsonb, 'Crisis alimentaria en Oriente Medio y Norte de África, inflación de precios', '#ff6600'),
  ('golfo-gas-natural', 'Golfo Pérsico - Gas Natural Licuado', 'Qatar/UAE', 25.2548, 55.3643, 'Extracción de Recursos', 'MEDIA', 45, '["Energía","Manufactura","Química"]'::jsonb, 'Golfo Pérsico produce el 45% del gas natural licuado global', '["Tensiones regionales Iran-USA","Ruta marítima a través de Ormuz","Dependencia de suministros chinos para equipos","Cambio climático y calor extremo"]'::jsonb, '["Qatar Petroleum","ADNOC","Shell","Todas compañías energéticas"]'::jsonb, 'Crisis energética global, especialmente en Asia y Europa', '#ffaa00'),
  ('taiwán-encapsulado', 'Taiwán - Encapsulado y Pruebas de Chips', 'Taiwán', 23.8978, 120.9605, 'Manufactura', 'ALTA', 65, '["Semiconductores","Electrónica"]'::jsonb, 'Taiwán encapsula y prueba el 65% de los chips globales, paso final en fabricación', '["Concentración geográfica","Dependencia de materiales de otros países","Amenaza militar directa de China","Capacidad limitada de expansión"]'::jsonb, '["Todos fabricantes de chips","Apple","Qualcomm"]'::jsonb, 'Detención de producción de chips a nivel mundial', '#ff6600')
on conflict (id) do nothing;
